In [3]:
import pandas as pd
import requests

In [4]:
url = "https://api.github.com/repos/pandas-dev/pandas/issues"

In [5]:
resp = requests.get(url)
resp

In [6]:
data = resp.json()
data[0]['title']

'BUG: DataFrameGroupBy.transform with axis=1 fails'

In [7]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

,number,title,labels,state
0,36308,BUG: DataFrameGroupBy.transform with axis=1 fails,"[{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...",open
1,36307,TYPING: `df.columns.levels` raises mypy error ...,[],open
2,36306,BUG: DataFrameGroupBy.apply with as_index Fals...,"[{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...",open
3,36305,ENH: Support MultiIndex columns in parquet (#3...,[],open
4,36304,PERF: creating string Series/Arrays from seque...,[],open
5,36303,REGR: Fix IntegerArray unary ops regression,"[{'id': 1817503692, 'node_id': 'MDU6TGFiZWwxOD...",open
6,36302,BUG: DataFrameGroupBy.__getitem__ should warn ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
7,36301,REF: de-duplicate sort_values,[],open
8,36300,[DOC]: Improve drop isin docs,[],open
9,36299,[BUG]: Index.union() inconsisten with non-uniq...,[],open
10,36298,Py39 Support - Remove Deprecated Unicode Lengt...,[],open
11,36297,BUG: fix duplicate entries in LaTeX List of Ta...,[],open
12,36296,BLD/CI: 3.9 support,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
13,36295,CLN: Remove trailing commas,"[{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...",open
14,36294,BUG:unexpected behavior of pandas 1.1.1 dt.nor...,"[{'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgx...",open
15,36293,BUG: `DataFrame.drop` fails when there is a mu...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
16,36291,BUG: pandas series creation fails with Overflo...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
17,36290,[BUG]: Fix ValueError in concat() when at leas...,[],open
18,36289,BUG: Index.union() drops Index component for d...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
19,36288,ERR: Report key on (unsupported) indexing errors,"[{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...",open
20,36287,ENH: support of pandas.DataFrame.hist for date...,[],open
21,36286,ENH: allow sort_values to use the natural sort...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
22,36284,"DOC: Fixed type hints for GroupBy.{any, all}",[],open
23,36283,TST: #31922 assert no segmentation fault with ...,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
24,36282,REF: de-duplicate _wrap_joined_index,[],open
25,36281,QST: Appending to pandas DataFrames,"[{'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0...",open
26,36280,PERF: CategoricalDtype.__eq__,[],open
27,36279,QST: Python 3.9 testing in CI,"[{'id': 717120670, 'node_id': 'MDU6TGFiZWw3MTc...",open
28,36278,[TST]: Add test for 24768,"[{'id': 13098779, 'node_id': 'MDU6TGFiZWwxMzA5...",open
29,36277,ENH: add peek function,"[{'id': 219960758, 'node_id': 'MDU6TGFiZWwyMTk...",open